### ISSUE TITLE
Needs a code of conduct

### ISSUE THREAD

**Issue by L-Nadav** [TrvsF/wurst-plus-three#10]
To provide a safe and inclusive place for all developers to be able to work on this client I recommend a code of conduct be added to prevent bad actors from excluding people who may be discriminated against. I highly recommend not accepting any commits which may non gender ambiguous wording as to not exclude women and other minorities from this project. I also recommend removing any persons who have or may have said anything sexist, racist or transphobic. Please read https://opensource.guide/code-of-conduct/ for more information.
Sincerely - Lnadav

**Comment by milse113** [comment]
I concur

**Comment by dansfilms** [comment]
I concur

**Comment by RemainingToast** [comment]
I concur

**Comment by Gav06** [comment]
🐵

**Comment by 7BT** [comment]
> Lnadav

I Absolutely Agree with this, get rid of those stupid people and make them use phobos kek

**Comment by s0daa** [comment]
i concur

**Comment by Madmegsox1** [comment]
@TrvsF do this cba

**Comment by L-Nadav** [comment]
@Madmegsox1 if you would like I can write up a brief CoC by tomorow?

**Comment by TrvsF** [comment]
@L-Nadav yes, that would be very useful

**Comment by Crystallinqq** [comment]
code on conduct deez nuts on yo mouth

**Comment by Crystallinqq** [comment]
> @Madmegsox1 if you would like I can write up a brief CoC by tomorow?

sussy.... sussy baka./.,...

**Comment by TrvsF** [comment]
> 
> 
> code on conduct deez nuts on yo mouth

please dont undermind this very important addition, we support all genders here (and then maybe dominika will help 😻)

**Comment by snuckdev** [comment]
Its a rat

**Comment by omegabr99** [comment]
> > code on conduct deez nuts on yo mouth
> 
> please dont undermind this very important addition, we support all genders here (and then maybe dominika will help 😻)

average dominika fan vs average mr qq enjoyer
