### ISSUE TITLE
[BUG] key pearl able to crash game on multiplayer servers

### ISSUE THREAD

**Issue by Gaamr** [TrvsF/wurst-plus-three#101]
Key pearl with the right settings is able to fully crash my game in multiplayer when it is not in my hotbar.

turn on key pearl
set key to middle click and turn on middle click pearl

the game *should* crash. make sure you are on a multiplayer server, ive only tested this on 5b5t.org and 2b2tpvp.org so it may just be those servers, or it could be me being a dumbass

i (for some reason) cant post videos because they are for some reason mkv because i recorded with obs, if you need the video, you can dm me on discord at Gamr#6169

**Comment by BiGgweeb** [comment]
Mine seems to work fine and when I run out of ender pearls in my hotbar, it kicks me (which is normal). Can you send logs of what happened? I also tried on the specified servers and more, and all work fine.
