### ISSUE TITLE
[SUGGESTION] Mod enable notification in chat

### ISSUE THREAD

**Issue by Davryii** [TrvsF/wurst-plus-three#120]
**Is your feature request related to a problem? Please describe.**

 I'm always frustrated when i think i have something enabled but i do not

**Describe the solution you'd like**

Make a chat notification everytime you turn on a module (eg. "Ca has been turned on" or something like this)

**Describe alternatives you've considered**

i dont have any

**Additional context**

**Comment by wallhacks0** [comment]
this already a feature in the chat category
