### ISSUE TITLE
[BUG] zori compability

### ISSUE THREAD

**Issue by w0rl3x** [TrvsF/wurst-plus-three#126]
even making request = 0 in MixinMinecraft cant fix crashes with zori 1.2.2 (https://github.com/slol2/Zori-1.2.2-Source-Leak)

**Comment by wallhacks0** [comment]
lmao zuri users in 2021 most useless hack ever

**Comment by wallhacks0** [comment]
@w0rl3x im not in to running rats so if you send crashlog to wallhacks#6969 I might fix it

**Comment by w0rl3x** [comment]
> @w0rl3x im not in to running rats so if you send crashlog to wallhacks#6969 I might fix it

how can it be ratted while its on github

**Comment by dldlglglgluyl** [comment]
that doesnt mean anything??
theres rats on github

**Comment by wallhacks0** [comment]
I love this issue

**Comment by RandomClientCollector** [comment]
Oh nice another rat for my collection😳
