### ISSUE TITLE
Download 404 not found

### ISSUE THREAD

**Issue by HW12345** [TrvsF/wurst-plus-three#19]
Build failed, so I went to the download page and it said 404 not found. Plz fix

**Comment by Madmegsox1** [comment]
Ill look into it

**Comment by Madmegsox1** [comment]
could you send me the build error

**Comment by HW12345** [comment]
* Where:
Build file 'D:\TEMP\wurst-plus-three-main\build.gradle' line: 18

* What went wrong:
A problem occurred evaluating root project 'wurst-plus-three-main'.
> 'org.gradle.api.tasks.TaskOutputs org.gradle.api.internal.TaskOutputsInternal.dir(java.lang.Object)'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8.2/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by HW12345** [comment]
> could you send me the build error

sent btw can you give me a jar?

**Comment by HW12345** [comment]
> could you send me the build error

build again:
> Task :recompileMc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recompileMc'.
> Cannot invoke "String.split(String)" because "currentExtDirs" is null

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.9/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 5m 47s
11 actionable tasks: 11 executed

**Comment by TrvsF** [comment]
ensure you're using gradle 4 and jdk 1.8, also the build on github is working for me, try this link https://github.com/TrvsF/wurst-plus-three/releases/download/0.4.0/WurstplusThree.v0.4.0.jar

**Comment by HW12345** [comment]
thanks
