### ISSUE TITLE
Crashes when the home screen loads

### ISSUE THREAD

**Issue by aeoaeoaeo** [TrvsF/wurst-plus-three#25]
mc crashes as soon as the home screen loads, even when I am not using any other mods

**Comment by Turkishinqq** [comment]
Congratulations You Dowload Backdoor Say bye your accounts and your credit card

**Comment by Madmegsox1** [comment]
Can you send you mc log dm on discord Madmeg#4882

**Comment by dremonq** [comment]
maybe add -noverify

**Comment by aeoaeoaeo** [comment]
it worked when I used a different directory so I have no idea what the problem was
