### ISSUE TITLE
nice decomp 

### ISSUE THREAD

**Issue by h0lloww** [TrvsF/wurst-plus-three#5]
![cooldecomp](https://user-images.githubusercontent.com/64690335/116791098-bf02b300-aac0-11eb-9bb4-27e88007436e.png)

Advanced decompilation methods free download 100% safe

**Comment by Madmegsox1** [comment]
Yo, you can now skid this!

**Comment by dabigbulletz638** [comment]
> 
> 
> ![cooldecomp](https://user-images.githubusercontent.com/64690335/116791098-bf02b300-aac0-11eb-9bb4-27e88007436e.png)
> 
> Advanced decompilation methods free download 100% safe

bro u know ur down bad when ur getting humiliated by hollow

**Comment by TrvsF** [comment]
oh, didn't release you made 2 issues, you must still be mad over this https://github.com/TrvsF/wurstplus-two/pull/94 
im sorry

**Comment by h0lloww** [comment]
very mad... please add it im begging you

![wtfcaughtpasting](https://user-images.githubusercontent.com/64690335/116859738-24fa5200-ac09-11eb-8b69-4b76bffb22a3.png)
also whats up with this

**Comment by TrvsF** [comment]
still don't get it, can you add some more circles please?

**Comment by dabigbulletz638** [comment]
I'm not intelligent or anything but it seems like your CFR/FernFlower decompilation tool has failed in multiple spots. While we are on the topic of decompiler errors take a look at the method below...

https://github.com/TrvsF/wurst-plus-three/blob/830219be0e60e201b4a5d73f1a96ce82c9b4e39e/src/main/java/me/travis/wurstplusthree/util/CrystalUtil.java#L101

Is it really necessary to skid a sphere method that is just looping on the x,y,z or is this just some full skid stuff or what?? People should just use Phobos 1.9 because this is basically that but with some random LEGO™ modules pasted in the mix

**Comment by h0lloww** [comment]
damnnn kami method from 2018

**Comment by h0lloww** [comment]
also i think someone pasted in some licensed code man...

https://www.curseforge.com/minecraft/mc-mods/better-chat

**Comment by TrvsF** [comment]
whollow please stop posting you're making bullet look stupid by association, the better chat licence is under gpl-3 https://github.com/LlamaLad7/Better-Chat

bullet i don't have time to decompile and remap phobos (again) myself so i used this repo : https://github.com/Hqrion/Phobos-1.9.0-BUILDABLE-SRC becuase anyone who has the time to program their own crystal damage system needs to go outside

**Comment by h0lloww** [comment]
> whollow please stop posting you're making bullet look stupid by association, the better chat licence is under gpl-3 https://github.com/LlamaLad7/Better-Chat
> 
> bullet i don't have time to decompile and remap phobos (again) myself so i used this repo : https://github.com/Hqrion/Phobos-1.9.0-BUILDABLE-SRC becuase anyone who has the time to program their own crystal damage system needs to go outside

is it really that hard to look in the minecraft source?

also i dont study licenses cuz i dont paste random forge mods from curseforge

**Comment by h0lloww** [comment]
also why dont you just credit llamalad 

he worked way harder on a simple chat animation mod than u did on this shitty excuse of a client

**Comment by Madmegsox1** [comment]
> I'm not intelligent or anything but it seems like your CFR/FernFlower decompilation tool has failed in multiple spots. While we are on the topic of decompiler errors take a look at the method below...
> 
> https://github.com/TrvsF/wurst-plus-three/blob/830219be0e60e201b4a5d73f1a96ce82c9b4e39e/src/main/java/me/travis/wurstplusthree/util/CrystalUtil.java#L101
> 
> Is it really necessary to skid a sphere method that is just looping on the x,y,z or is this just some full skid stuff or what?? People should just use Phobos 1.9 because this is basically that but with some random LEGO™ modules pasted in the mix


Hum, I'm not sure what you are suggesting, that the way we iterate through an array of Vec3d's is incorrect or/and inefficient, because if you have a better method feel free to make pr!

**Comment by h0lloww** [comment]
nah its good man 

while (true)

**Comment by Madmegsox1** [comment]
was I taking to you?

**Comment by h0lloww** [comment]
I dont know man I aint readin yo shit 😀

**Comment by NirvanaNevermind** [comment]
Gotta say I'm disappointed, 
also hey Travis, been months since I've heard of you, and Hollow probably been a few weeks

**Comment by Gav06** [comment]
phobos paste

**Comment by 2wu** [comment]
I be Saucin All day All night
