### ISSUE TITLE
if ur holding obsidian when u turn on ac it places obsidian

### ISSUE THREAD

**Issue by The-Forecaster** [TrvsF/wurst-plus-three#70]
Use Player.syncCurrentPlayItem to stop this, also stop using phobos events they're pretty chinese

**Comment by Cyrogigabyte** [comment]
phobos 1.7.2 is written in chinese

**Comment by OlDestiny** [comment]
ching chong

**Comment by HAV0X1014** [comment]
TROLLED

**Comment by Cyrogigabyte** [comment]
> ching chong

**Comment by Madmegsox1** [comment]
should be fixed in #78
