### ISSUE TITLE
Safe?

### ISSUE THREAD

**Issue by Cyrogigabyte** [TrvsF/wurst-plus-three#71]
Is dis client safe and why is phobos chinese

**Comment by Madmegsox1** [comment]
yes and phobos is bad

**Comment by BiGgweeb** [comment]
Yes it is safe. Looked through by many people.

**Comment by Cyrogigabyte** [comment]
> Yes it is safe. Looked through by many people.

by who?

**Comment by phobologicalt** [comment]
> > Yes it is safe. Looked through by many people.
> 
> by who?

joe

**Comment by Nirjal112233** [comment]
idk is it safe
