### ISSUE TITLE
not working with certain client

### ISSUE THREAD

**Issue by SCO69** [TrvsF/wurst-plus-three#77]
i tried running it with many clients, but pyro seems to be the one it doesnt work well with

**Comment by Eonexe** [comment]
it also seems to have issues with konas and phobos im pretty sure

**Comment by The-Forecaster** [comment]
from what ive seen, konas and pyro dont work with w+3, post some others if you notice they dont work

**Comment by jumboman32** [comment]
stop using multiple shit paste clients and you wont run into issues

**Comment by zTrickyy** [comment]
i also cant use it with my creepy salhack + inertia

**Comment by notperry1234567890** [comment]
> i also cant use it with my creepy salhack + inertia

If u actually use those quit.

**Comment by zTrickyy** [comment]
> > i also cant use it with my creepy salhack + inertia
> 
> If u actually use those quit.

why? i use inertia for duping and salhack for other features i want to use w+3 for combat

**Comment by Eonexe** [comment]
> If u guy have issues with konas please send me the crash log as I do not have that client same with rusher hack

ill dm you them

**Comment by TediousDuskFall** [comment]
> If u guy have issues with konas please send me the crash log as I do not have that client same with rusher hack

its not that it crashes w/ konas its just some modules completely dont work, once you pair konas with wp3 velocity guimove and a few other modules from koans dont work at all

**Comment by wyvest** [comment]
> > If u guy have issues with konas please send me the crash log as I do not have that client same with rusher hack
> 
> its not that it crashes w/ konas its just some modules completely dont work, once you pair konas with wp3 velocity guimove and a few other modules from koans dont work at all

not sure about the code of this or konas, but this sounds like a mixin conflict
