### ISSUE TITLE
Broken Modules [BUG]

### ISSUE THREAD

**Issue by Cyrogigabyte** [TrvsF/wurst-plus-three#80]
**Describe the bug**

**To Reproduce**
1. Turn on module: 'offhand'
2. Set the setting to 'crystal'
3. See error autototem fail

**Expected behavior**
Doesn't Change to totem
**Screenshots**
Add screenshots or videos to help explain the problem.

**Additional context**
It might be cuz I have like 1k ping

**Comment by Cyrogigabyte** [comment]
I think it toggles offhand

**Comment by Madmegsox1** [comment]
Maybe turn your totem health to 16
