### ISSUE TITLE
[SUGGESTION] elytrafly?

### ISSUE THREAD

**Issue by Gaamr** [TrvsF/wurst-plus-three#94]
is there any plan to add stuff like elytrafly or keep it as a combat-based client?

**Comment by WMSGaming** [comment]
> is there any plan to add stuff like elytrafly or keep it as a combat-based client?

sounds like a good idea, even if its basic and only works on servers like 5b5t it would be cool

**Comment by Eonexe** [comment]
Just use 2 clients 🤪
